version: "2"
services:
    app:
        restart: always
        build: .
        ports:
            - "8004:8080"
        volumes:
            - ./:/go/src
volumes:
    modules:
        driver: "local"

